apiVersion: k8s.mariadb.com/v1alpha1
kind: Backup
metadata:
  name: {{ .Values.backup.name | quote }}
spec:
  mariaDbRef:
    name: {{ .Values.backup.mariaDbRefName | quote }}
  inheritMetadata:
    annotations:
      database.myorg.io: {{ .Values.backup.inheritMetadata.annotations.databaseMyorgIo | quote }}
  podMetadata:
    labels:
      sidecar.istio.io/inject: {{ .Values.backup.podMetadata.labels.sidecarIstioIoInject | quote }}
  serviceAccountName: {{ .Values.backup.serviceAccountName | quote }}
  compression: {{ .Values.backup.compression | quote }}
  storage:
    persistentVolumeClaim:
      resources:
        requests:
          storage: {{ .Values.backup.storage.persistentVolumeClaim.resources.requests.storage | quote }}
      accessModes:
        - {{ .Values.backup.storage.persistentVolumeClaim.accessModes | quote }}
  args:
    - {{ .Values.backup.args.singleTransaction | quote }}
    - {{ .Values.backup.args.allDatabases | quote }}
    - {{ .Values.backup.args.verbose | quote }}
  resources:
    requests:
      cpu: {{ .Values.backup.resources.requests.cpu | quote }}
      memory: {{ .Values.backup.resources.requests.memory | quote }}
    limits:
      cpu: {{ .Values.backup.resources.limits.cpu | quote }}
      memory: {{ .Values.backup.resources.limits.memory | quote }}
  affinity:
    antiAffinityEnabled: {{ .Values.backup.affinity.antiAffinityEnabled | quote }}