apiVersion: k8s.mariadb.com/v1alpha1
kind: Connection
metadata:
  name: {{ include "mariadb.fullname" . }}-connection-custom-dsn
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
spec:
  mariaDbRef:
    name: {{ .Values.connectionCustomDsn.mariaDbRefName | default (include "mariadb.fullname" .) }}
  dsn: {{ .Values.connectionCustomDsn.dsn | quote }}
  secretName: {{ .Values.connectionCustomDsn.secretName | quote }}
  secretTemplate:
    metadata:
      labels:
        k8s.mariadb.com/connection: {{ .Values.connectionCustomDsn.secretTemplate.metadata.labels.connection | quote }}
      annotations:
        k8s.mariadb.com/connection: {{ .Values.connectionCustomDsn.secretTemplate.metadata.annotations.connection | quote }}
    key: {{ .Values.connectionCustomDsn.secretTemplate.key | quote }}
