apiVersion: k8s.mariadb.com/v1alpha1
kind: Connection
metadata:
  name: {{ include "mariadb.fullname" . }}-connection-custom-dsn
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
spec:
  mariaDbRef:
    name: {{ .Values.connectionCustomDsn.mariaDbRefName | default (include "mariadb.fullname" .) }}
  username: {{ .Values.connectionCustomDsn.username | quote }}
  passwordSecretKeyRef:
    name: {{ .Values.connectionCustomDsn.passwordSecretKeyRef.name | quote }}
    key: {{ .Values.connectionCustomDsn.passwordSecretKeyRef.key | quote }}
  database: {{ .Values.connectionCustomDsn.database | quote }}
  params:
    parseTime: {{ .Values.connectionCustomDsn.params.parseTime | quote }}
    timeout: {{ .Values.connectionCustomDsn.params.timeout | quote }}
  secretName: {{ .Values.connectionCustomDsn.secretName | quote }}
  secretTemplate:
    metadata:
      labels:
        k8s.mariadb.com/connection: {{ .Values.connectionCustomDsn.secretTemplate.metadata.labels.connection | quote }}
      annotations:
        k8s.mariadb.com/connection: {{ .Values.connectionCustomDsn.secretTemplate.metadata.annotations.connection | quote }}
    key: {{ .Values.connectionCustomDsn.secretTemplate.key | quote }}
    usernameKey: {{ .Values.connectionCustomDsn.secretTemplate.usernameKey | quote }}
    passwordKey: {{ .Values.connectionCustomDsn.secretTemplate.passwordKey | quote }}
    hostKey: {{ .Values.connectionCustomDsn.secretTemplate.hostKey | quote }}
    portKey: {{ .Values.connectionCustomDsn.secretTemplate.portKey | quote }}
    databaseKey: {{ .Values.connectionCustomDsn.secretTemplate.databaseKey | quote }}
  healthCheck:
    interval: {{ .Values.connectionCustomDsn.healthCheck.interval | quote }}
    retryInterval: {{ .Values.connectionCustomDsn.healthCheck.retryInterval | quote }}
  serviceName: {{ .Values.connectionCustomDsn.serviceName | quote }}
