apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: {{ include "mariadb.fullname" . }}-init-mariabackup
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
spec:
  initContainers:
    - image: {{ .Values.mariadbInitMariabackup.initContainers[0].image | quote }}
      args:
        - mariadb-backup
        - --copy-back
        - --target-dir=/var/mariadb/backup/
  volumes:
    - name: mariabackup
      persistentVolumeClaim:
        claimName: {{ .Values.mariadbInitMariabackup.volumes[0].persistentVolumeClaim.claimName | default "mariabackup" | quote }}
  volumeMounts:
    - name: mariabackup
      mountPath: {{ .Values.mariadbInitMariabackup.volumeMounts[0].mountPath | default "/var/mariadb/backup/" | quote }}
  storage:
    size: {{ .Values.mariadbInitMariabackup.storage.size | default "1Gi" }}
