apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: {{ .Values.mariadbPasswordPlugin.name }}
spec:
  rootPasswordSecretKeyRef:
    name: {{ .Values.mariadbPasswordPlugin.rootPasswordSecretKeyRef.name }}
    key: {{ .Values.mariadbPasswordPlugin.rootPasswordSecretKeyRef.key }}

  username: {{ .Values.mariadbPasswordPlugin.username }}
  passwordSecretKeyRef:
    name: {{ .Values.mariadbPasswordPlugin.passwordSecretKeyRef.name }}
    key: {{ .Values.mariadbPasswordPlugin.passwordSecretKeyRef.key }}
  # passwordHashSecretKeyRef:
  #   name: {{ .Values.mariadbPasswordPlugin.passwordHashSecretKeyRef.name }}
  #   key: {{ .Values.mariadbPasswordPlugin.passwordHashSecretKeyRef.key }}
  passwordPlugin:
    pluginNameSecretKeyRef:
        name: {{ .Values.mariadbPasswordPlugin.passwordPlugin.pluginNameSecretKeyRef.name }}
        key: {{ .Values.mariadbPasswordPlugin.passwordPlugin.pluginNameSecretKeyRef.key }}
    pluginArgSecretKeyRef:
        name: {{ .Values.mariadbPasswordPlugin.passwordPlugin.pluginArgSecretKeyRef.name }}
        key: {{ .Values.mariadbPasswordPlugin.passwordPlugin.pluginArgSecretKeyRef.key }}
  database: {{ .Values.mariadbPasswordPlugin.database }}
  
  connection:
    secretName: {{ .Values.mariadbPasswordPlugin.connection.secretName }}
    secretTemplate:
      key: {{ .Values.mariadbPasswordPlugin.connection.secretTemplate.key }}
    healthCheck:
      interval: {{ .Values.mariadbPasswordPlugin.connection.healthCheck.interval }}
      retryInterval: {{ .Values.mariadbPasswordPlugin.connection.healthCheck.retryInterval }}
    params:
      parseTime: {{ .Values.mariadbPasswordPlugin.connection.params.parseTime | quote }}

  storage:
    size: {{ .Values.mariadbPasswordPlugin.storage.size }}

  service:
    type: {{ .Values.mariadbPasswordPlugin.service.type }}
    metadata:
      annotations:
        metallb.universe.tf/loadBalancerIPs: {{ .Values.mariadbPasswordPlugin.service.annotations.metallbLoadBalancerIP }}
