apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: {{ .Values.mariadb.name }}
spec:
  rootPasswordSecretKeyRef:
    name: {{ .Values.mariadb.rootPasswordSecretKeyRef.name }}
    key: {{ .Values.mariadb.rootPasswordSecretKeyRef.key }}

  username: {{ .Values.mariadb.username }}
  passwordSecretKeyRef:
    name: {{ .Values.mariadb.passwordSecretKeyRef.name }}
    key: {{ .Values.mariadb.passwordSecretKeyRef.key }}
    generate: {{ .Values.mariadb.passwordSecretKeyRef.generate }}
  database: {{ .Values.mariadb.database }}

  port: {{ .Values.mariadb.port }}

  storage:
    size: {{ .Values.mariadb.storage.size }}

  service:
    type: {{ .Values.mariadb.service.type }}
    metadata:
      annotations:
        metallb.universe.tf/loadBalancerIPs: {{ .Values.mariadb.service.annotations.metallbLoadBalancerIP }}

  myCnf: |
{{ .Values.mariadb.myCnf | indent 4 }}

  resources:
    requests:
      cpu: {{ .Values.mariadb.resources.requests.cpu }}
      memory: {{ .Values.mariadb.resources.requests.memory }}
    limits:
      memory: {{ .Values.mariadb.resources.limits.memory }}

  metrics:
    enabled: {{ .Values.mariadb.metrics.enabled }}
