apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: {{ .Values.mariadbMinimal.name }}
spec:
  rootEmptyPassword: {{ .Values.mariadbMinimal.rootEmptyPassword }}
  storage:
    ephemeral: {{ .Values.mariadbMinimal.storage.ephemeral }}
