apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: {{ include "mariadb.fullname" . }}-from-backup
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
spec:
  storage:
    size: {{ .Values.mariadbFromBackup.storage.size | default "1Gi" }}
  bootstrapFrom:
    backupRef:
      name: {{ .Values.mariadbFromBackup.bootstrapFrom.backupRef.name | quote }}
    targetRecoveryTime: {{ .Values.mariadbFromBackup.bootstrapFrom.targetRecoveryTime | quote }}
    restoreJob:
      metadata:
        labels:
          sidecar.istio.io/inject: {{ .Values.mariadbFromBackup.bootstrapFrom.restoreJob.metadata.labels.sidecarIstioIoInject | quote }}
      args:
        - {{ .Values.mariadbFromBackup.bootstrapFrom.restoreJob.args.verbose | quote }}
      affinity:
        antiAffinityEnabled: {{ .Values.mariadbFromBackup.bootstrapFrom.restoreJob.affinity.antiAffinityEnabled | default true }}
      resources:
        requests:
          cpu: {{ .Values.mariadbFromBackup.bootstrapFrom.restoreJob.resources.requests.cpu | default "100m" }}
          memory: {{ .Values.mariadbFromBackup.bootstrapFrom.restoreJob.resources.requests.memory | default "128Mi" }}
        limits:
          memory: {{ .Values.mariadbFromBackup.bootstrapFrom.restoreJob.resources.limits.memory | default "1Gi" }}
