apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: {{ .Values.mariadbReplication.name }}
spec:
  rootPasswordSecretKeyRef:
    name: {{ .Values.mariadbReplication.rootPasswordSecretKeyRef.name }}
    key: {{ .Values.mariadbReplication.rootPasswordSecretKeyRef.key }}

  storage:
    size: {{ .Values.mariadbReplication.storage.size }}

  replicas: {{ .Values.mariadbReplication.replicas }}

  replication:
    enabled: {{ .Values.mariadbReplication.replication.enabled }}

  service:
    type: {{ .Values.mariadbReplication.service.type }}
    metadata:
      annotations:
        metallb.universe.tf/loadBalancerIPs: {{ .Values.mariadbReplication.service.annotations.metallbLoadBalancerIP }}

  primaryService:
    type: {{ .Values.mariadbReplication.primaryService.type }}
    metadata:
      annotations:
        metallb.universe.tf/loadBalancerIPs: {{ .Values.mariadbReplication.primaryService.annotations.metallbLoadBalancerIP }}

  secondaryService:
    type: {{ .Values.mariadbReplication.secondaryService.type }}
    metadata:
      annotations:
        metallb.universe.tf/loadBalancerIPs: {{ .Values.mariadbReplication.secondaryService.annotations.metallbLoadBalancerIP }}

  metrics:
    enabled: {{ .Values.mariadbReplication.metrics.enabled }}
