apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "mariadb.fullname" . }}-role
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/status"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "mariadb.fullname" . }}-rolebinding
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "mariadb.fullname" . }}-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "mariadb.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io