apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "mariadb.fullname" . }}
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ include "mariadb.name" . }}
  endpoints:
    - port: db
      interval: {{ .Values.serviceMonitor.interval | quote }}
      path: /metrics
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}