apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: {{ include "mariadb.fullname" . }}-user
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
spec:
  name: {{ .Values.user.name | default (include "mariadb.fullname" .) }}
  mariaDbRef:
    name: {{ .Values.user.mariaDbRefName | default (include "mariadb.fullname" .) }}
  passwordSecretKeyRef:
    name: {{ .Values.user.passwordSecretKeyRef.name | quote }}
    key: {{ .Values.user.passwordSecretKeyRef.key | quote }}
  maxUserConnections: {{ .Values.user.maxUserConnections | default 10 }}
  host: {{ .Values.user.host | default '"%"' }}
  cleanupPolicy: {{ .Values.user.cleanupPolicy | default "Delete" }}
  requeueInterval: {{ .Values.user.requeueInterval | default "30s" }}
  retryInterval: {{ .Values.user.retryInterval | default "5s" }}
