apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: {{ include "mariadb.fullname" . }}-user-password-plugin
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
spec:
  name: {{ .Values.userPasswordPlugin.name | default (include "mariadb.fullname" .) }}
  mariaDbRef:
    name: {{ .Values.userPasswordPlugin.mariaDbRefName | default (include "mariadb.fullname" .) }}
  passwordSecretKeyRef:
    name: {{ .Values.userPasswordPlugin.passwordSecretKeyRef.name | quote }}
    key: {{ .Values.userPasswordPlugin.passwordSecretKeyRef.key | quote }}
  authenticationPlugin: {{ .Values.userPasswordPlugin.authenticationPlugin | quote }}
  host: {{ .Values.userPasswordPlugin.host | default '"%"' }}
  cleanupPolicy: {{ .Values.userPasswordPlugin.cleanupPolicy | default "Delete" }}
  requeueInterval: {{ .Values.userPasswordPlugin.requeueInterval | default "30s" }}
  retryInterval: {{ .Values.userPasswordPlugin.retryInterval | default "5s" }}
