apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: {{ .Values.userPasswordPlugin.name | default "user-password-plugin" }}
spec:
  mariaDbRef:
    name: {{ .Values.userPasswordPlugin.mariaDbRefName | default "mariadb" }}
  passwordPlugin:
    pluginNameSecretKeyRef:
      name: {{ .Values.userPasswordPlugin.pluginNameSecretKeyRef.name | default "mariadb-auth" | quote }}
      key: {{ .Values.userPasswordPlugin.pluginNameSecretKeyRef.key | default "nativePasswordPlugin" | quote }}
    pluginArgSecretKeyRef:
      name: {{ .Values.userPasswordPlugin.pluginArgSecretKeyRef.name | default "mariadb-auth" | quote }}
      key: {{ .Values.userPasswordPlugin.pluginArgSecretKeyRef.key | default "passwordHash" | quote }}
  host: {{ .Values.userPasswordPlugin.host | default '"%"' }}
