apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: {{ include "mariadb.fullname" . }}-user-password-hash
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
spec:
  name: {{ .Values.userPasswordHash.name | default (include "mariadb.fullname" .) }}
  mariaDbRef:
    name: {{ .Values.userPasswordHash.mariaDbRefName | default (include "mariadb.fullname" .) }}
  passwordHash: {{ .Values.userPasswordHash.passwordHash | quote }}
  host: {{ .Values.userPasswordHash.host | default '"%"' }}
  cleanupPolicy: {{ .Values.userPasswordHash.cleanupPolicy | default "Delete" }}
  requeueInterval: {{ .Values.userPasswordHash.requeueInterval | default "30s" }}
  retryInterval: {{ .Values.userPasswordHash.retryInterval | default "5s" }}
