apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: {{ .Values.userPasswordHash.name | default "user-password-hash" }}
spec:
  mariaDbRef:
    name: {{ .Values.userPasswordHash.mariaDbRefName | default "mariadb" }}
  passwordHashSecretKeyRef:
    name: {{ .Values.userPasswordHash.passwordHashSecretKeyRef.name | default "mariadb-auth" | quote }}
    key: {{ .Values.userPasswordHash.passwordHashSecretKeyRef.key | default "passwordHash" | quote }}
  host: {{ .Values.userPasswordHash.host | default "%" }}