apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: {{ .Values.userTls.name | default (include "mariadb.fullname" .) }}
spec:
  name: {{ .Values.userTls.username | default "alice" }}
  mariaDbRef:
    name: {{ .Values.userTls.mariaDbRefName | default (include "mariadb.fullname" .) }}
  require:
    issuer: {{ .Values.userTls.require.issuer | quote }}
    subject: {{ .Values.userTls.require.subject | quote }}
  host: {{ .Values.userTls.host | default '"%"' }}
